# Site settings
title: Syncronyze
description: Syncronyze
url: syncronyze.net

# User settings
username: Nick Dilallo
user_title: Creator
email: nick@syncronyze.net
alias: syncronyze

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
